spring:
  datasource:
    url: jdbc:mysql://mysql:3306/vueboot?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379
