spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueboot?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
server:
  port: 8081


shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
    password: root



